#!/bin/sh
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
mkdir -p "$XDG_CACHE_HOME/xdg-xmenu"
MENU_FILE=$XDG_CACHE_HOME/xdg-xmenu/menu
xdg-xmenu -t st > "$MENU_FILE"
xmenu "$@" < "$MENU_FILE" | sh &
